Fixed some stuff around home folder

diff --git a/dot_config/zsh/work_alias b/dot_config/zsh/work_alias
--- a/dot_config/zsh/work_alias
+++ b/dot_config/zsh/work_alias
@@ -1,34 +1,5 @@
-readonly BASE_PATH="$HOME/Projects/CSTAF/sigtaf"
-readonly BACKEND_PATH="$BASE_PATH/sigtaf-backend"
-readonly FRONTEND_PATH="$BASE_PATH/sigtaf-frontend"
-
-function start-sigtaf() {
-	sudo -v 				# asks for sudo perms upfront								
-
-	while true
-	do
-		sudo -n true				# -n for non-interactive, if cache SOMEHOW fails, this subthread fails gracefully
-		sleep 60
-		kill -0 "$$" || exit    	# kill -0 "$$" kills this subprogram when it wakes up from 
-	done 2>/dev/null &				# sleep and realizes the main program isn't running anymore
-
-	echo $BACKEND_PATH
-	echo $FRONTEND_PATH
-	
-	parallel-update-repos $BACKEND_PATH	$FRONTEND_PATH	# Update both repositories
-
-	echo "Updating Backend"
-	( cd $BACKEND_PATH && make setup )		# Check for updates + resets DB
-
-	echo "Updating and starting Frontend"
-	( cd $FRONTEND_PATH && npm start )		# Spins up Backend
-	
-}
-alias up-sig=start-sigtaf
-
 function parallel-update-repos() {								# Must recieve at least one git repository path
 
-	echo $@
 	local projects=("$@")										# Takes ALL passed arguments into a local array
 	if [ ${#projects[@]} -eq 0 ]; then							# check if any projects were passed by parameter
 		echo "Error: No projects provided." >&2
@@ -59,7 +30,7 @@ function parallel-update-repos() {								# Must recieve at least one git reposi
 		wait
 	)
 	if [ -f "$err_file" ]; then									# Check if any background workers created the error file
-		rm "$err_file" # Clean up
+		rm "$err_file" 											# Clean up
 		echo "There was an error updating the projects!"
 		return 1
 	else
@@ -67,3 +38,31 @@ function parallel-update-repos() {								# Must recieve at least one git reposi
 		return 0
 	fi
 }
+
+readonly BASE_PATH="$HOME/Projects/CSTAF/sigtaf"
+readonly BACKEND_PATH="$BASE_PATH/sigtaf-backend"
+readonly FRONTEND_PATH="$BASE_PATH/sigtaf-frontend"
+
+function start-sigtaf() {
+	sudo -v 															# asks for sudo perms upfront								
+
+	while true
+	do
+		sudo -n true													# -n for non-interactive, if cache SOMEHOW fails, this subthread fails gracefully
+		sleep 60
+		kill -0 "$$" || exit    										# kill -0 "$$" kills this subprogram when it wakes up from 
+	done 2>/dev/null &													# Sleep and realizes the main program isn't running anymore
+	
+	parallel-update-repos $BACKEND_PATH	$FRONTEND_PATH					# Update both repositories
+
+	echo "Updating Backend"
+	( cd $BACKEND_PATH && make setup )									# Check for updates + resets DB
+
+	echo "Updating and starting Frontend"
+    ( cd "$FRONTEND_PATH" && npm start)									# Spin up frontend         
+    echo "Tailing backend logs..."
+    
+}
+alias up-sig=start-sigtaf
+
+alias sig-logs="docker logs -f sigtaf-backend"
